global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    metric_relabel_configs:
      - source_labels: [instance]
        regex: '^([^:]+:\d+)$'  # Keeps properly formatted host:port
        action: keep
      - source_labels: [instance]
        regex: '^:\d+$'  # Drops malformed :port entries
        action: drop